FROM python:3.10

ARG REDIS_HOST='c-c9qk44dr7ik3peg6bi8g.rw.mdb.yandexcloud.net'
ARG REDIS_PORT=6380
ARG REDIS_PASSWORD='Zaq12wsXCde3'

ARG PG_WAREHOUSE_HOST='rc1b-107jwcgucbmzzozk.mdb.yandexcloud.net'
ARG PG_WAREHOUSE_PORT=6432
ARG PG_WAREHOUSE_DBNAME='sprint9dwh'
ARG PG_WAREHOUSE_USER='s9sprint'
ARG PG_WAREHOUSE_PASSWORD='Zaq12wsXCde3'

RUN apt-get update -y

COPY . .

RUN pip install -r requirements.txt

RUN mkdir -p /crt
RUN wget "https://storage.yandexcloud.net/cloud-certs/CA.pem" --output-document /crt/YandexInternalRootCA.crt
RUN chmod 0600 /crt/YandexInternalRootCA.crt

WORKDIR /src
ENTRYPOINT ["python"]

CMD ["app.py"]